# Ajout de la colonne cat et première mise en forme des données

In [1]:
import pandas as pd
import re

In [2]:
"""
"week_day" au lieu de "day", ajout de "date" (ou "date" au lieu de "time") : à prendre en compte dans le modèle relationnel
"status" : à ajouter dans la table fatalities_report comme prévu dans la description
"year_built" : à supprimer dans les tables
"""

final_names =["identifiant",
              "week_day",
              "date",
              "time",
              "type_event",
              "phase",
              "location",
              "country",
              "total_occupants",
              "total_fatalities",
              "aircraft_damage",
              "aircraft_fate",
              "type_aircraft",
              "number_engines",
              "type_engines",
              "first_flight",
              "cycles",
              "total_airframe_hours",
              "registration",
              "c_n_msn",
              "operator",
              "nature",
              "flight_number",
              "departure_airport_name",
              "departure_airport_IATA",
              "departure_airport_ICAO",
              "departure_airport_country",
              "destination_airport_name",
              "destination_airport_IATA",
              "destination_airport_ICAO",
              "destination_airport_country",
              "crew_number",
              "passengers_number",
              "crew_fatalities",
              "passengers_fatalities",
              "collision_casualties",
              "ground_casualties",
              "status"]
#final_names
len(final_names)

38

In [3]:
names=["identifiant",
       "status",
       "date",
       "time",
       "type_aircraft",
       "operator",
       "operating_for",
       "on_behalf_of",
       "leased_from",
       "registration",
       "c_n_msn",
       "first_flight",
       "total_airframe_hrs",
       "year_built","engines",
       "cycles",
       "crew","passengers",
       "ground_casualties",
       "collision_casualties",
       "aircraft_damage",
       "aircraft_fate",
       "location",
       "phase",
       "nature",
       "departure_airport",
       "destination_airport",
       "flight_number",
       "probable_cause",
       "total"]
len(names)

30

In [4]:
annee = 2007
p=f"bonnes_donnees2/data_{annee}.csv"
dframe=pd.read_csv(p,sep=",",skiprows=[0],names=names)
if annee==1900 :
    dframe["date"]="xxxx"

In [5]:
dframe

,identifiant,status,date,time,type_aircraft,operator,operating_for,on_behalf_of,leased_from,registration,...,aircraft_damage,aircraft_fate,location,phase,nature,departure_airport,destination_airport,flight_number,probable_cause,total
0,20070101-0,Final,Monday 1 January 2007,ca 14:59,Boeing 737-4Q8,AdamAir,NaN,NaN,NaN,PK-KKW,...,Destroyed,Written off (damaged beyond repair),85 km (53.1 mls) W off Pambauang ( Indonesi...,En route (ENR),Domestic Scheduled Passenger,"Surabaya-Juanda Airport (SUB/WARR), Indonesia","Manado-Sam Ratulangi Airport (MDC/WAMM), Indon...",574,NaN,Fatalities: 102 / Occupants: 102
1,20070107-0,Final,Sunday 7 January 2007,20:02,Beechcraft A100 King Air,Transwest Air,NaN,NaN,NaN,C-GFFN,...,Destroyed,Written off (damaged beyond repair),"Sandy Bay Airport, SK ( Canada) \r\n",Approach (APR),Ambulance,"La Ronge Airport, SK (YVC/CYVC), Canada","Sandy Bay Airport, SK, Canada",350,NaN,Fatalities: 1 / Occupants: 4
2,20070109-0,Preliminary,Tuesday 9 January 2007,NaN,Antonov An-26B-100,Aeriantur-M Airlines,NaN,NaN,NaN,ER-26068,...,Destroyed,Written off (damaged beyond repair),near Balad Air Base ( Iraq) \r\n,Approach (APR),Int'l Non Scheduled Passenger,"Adana Airport (ADA/LTAF), Turkey","Balad Air Base, Iraq",NaN,NaN,Fatalities: 34 / Occupants: 35
3,20070109-1,Preliminary - official,Tuesday 9 January 2007,23:23,Learjet 24F,Ameristar Jet Charter,NaN,NaN,NaN,N444TW,...,Destroyed,Written off (damaged beyond repair),30 km (18.8 mls) E of Guadalajara-Miguel Hidal...,Approach (APR),Cargo,"Laredo International Airport, TX (LRD/KLRD), U...",Guadalajara-Don Miguel Hidalgo y Costilla Inte...,878,NaN,Fatalities: 2 / Occupants: 2
4,20070109-2,Final,Tuesday 9 January 2007,11:33,British Aerospace 3112 Jetstream 31,Peace Air,NaN,NaN,NaN,C-FBIP,...,Damaged beyond repair,NaN,"Fort St. John Airport, BC (YXJ) ( Canada) \r\n",Landing (LDG),Domestic Scheduled Passenger,"Grande Prairie Airport, AB (YQU/CYQU), Canada","Fort St. John Airport, BC (YXJ/CYXJ), Canada",905,NaN,Fatalities: 0 / Occupants: 12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,20071230-0,Preliminary,Sunday 30 December 2007,ca 11:30,GAF Nomad N.22B,Tentara Nasional Indonesia-AL (Navy),NaN,NaN,NaN,P-833,...,Damaged beyond repair,NaN,off Sabang ( Indonesia) \r\n,Approach (APR),Military,"Sabang-Maimun Saleh Airport (SBG/WITB), Indonesia","Medan-Polonia Airport (MES/WIMM), Indonesia",NaN,NaN,Fatalities: 5 / Occupants: 7
220,20071230-1,Final,Sunday 30 December 2007,11:27,Boeing 737-38J,Tarom,NaN,NaN,NaN,YR-BGC,...,Substantial,Written off (damaged beyond repair),Bucharest-Otopeni International Airport (OTP) ...,Takeoff (TOF),Int'l Non Scheduled Passenger,Bucharest-Otopeni International Airport (OTP/L...,"Sharm el Sheikh-Ophira Airport (SSH/HESH), Egypt",3107,NaN,Fatalities: 0 / Occupants: 123
221,20071231-0,Preliminary,Monday 31 December 2007,NaN,Antonov An-12BP,Africa West Airlines,NaN,NaN,NaN,UR-TSI,...,Substantial,Repaired,Freetown-Lungi International Airport (FNA) ( ...,Landing (LDG),Cargo,?,Freetown-Lungi International Airport (FNA/GFLL...,NaN,NaN,Fatalities: 0 / Occupants:
222,20079999-0,Preliminary,xx xxx 2007,NaN,Antonov An-12BP,Unknown,NaN,NaN,NaN,S9-DBP,...,Damaged beyond repair,NaN,Bunia Airport (BUX) ( Democratic Republic of...,Landing (LDG),Cargo,?,"Bunia Airport (BUX/FZKA), Democratic Republic ...",NaN,NaN,Fatalities: 0 / Occupants:
223,20079999-1,NaN,xx xxx 2007,NaN,Rockwell Sabreliner 60,Flight Research Inc.,NaN,NaN,NaN,N211BR,...,Damaged beyond repair,NaN,"Mojave Air & Space Port, CA (MHV) ( United S...",Standing (STD),-,-,-,NaN,NaN,Fatalities: 0 / Occupants: 0

In [6]:
p_record = f"record2/data_{annee}.csv"
record_names = ["identifiant","date","type_aircraft","registration","operator","fatalities","location","type_event"]
cols = [0,1,2,3,4,5,6,9]
dfrecord=pd.read_csv(p_record,sep=",",usecols=cols,skiprows=[0],names=record_names)
if annee==1900 :
    dfrecord["date"]="xxxx"

In [7]:
dfrecord

,identifiant,date,type_aircraft,registration,operator,fatalities,location,type_event
0,20071111-0,11-NOV-2007,Bombardier Global 5000,C-GXPR,Jetport,0,Fox Harbour ...,A1
1,20071115-0,15-NOV-2007,Airbus A340-642X,F-WWCJ,Airbus Industrie,0,Toulouse-Bla...,O1
2,20071129-0,29-NOV-2007,Beech 200 Super King Air,YV1387,Unknown,0,"Santa Inés, ...",A1
3,20071130-0,30-NOV-2007,DC-9-83 (MD-83),TC-AKM,"Atlasjet, lsf World Focus Airlines",57,near Isparta Airp...,A1
4,20071204-0,04-DEC-2007,Cessna 208B Grand Caravan,V3-HFS,Maya Island Air,0,Corozal Airp...,A1
...,...,...,...,...,...,...,...,...
219,20070623-1,23-JUN-2007,DHC-6 Twin Otter 300,7O-ADK,Yemenia Airways,1,An Naeem Air...,C1
220,20070625-0,25-JUN-2007,Antonov An-24B,XU-U4A,PMT Air,22,Phnom Damrey,A1
221,20070625-1,25-JUN-2007,DC 10-10,N450AX,"California Forestry and Fire Protection, opb 1...",0,"near Tehachapi, CA",A2
222,20070625-2,25-JUN-2007,Boeing 737-8AS (WL),EI-CSN,Ryanair,0,Venice-Trevi...,A2
223,20070626-0,26-JUN-2007,Let L-410UVP-E3,9Q-CTM,Business Aviation,0,near Brazzaville,A1

In [8]:
dframe.drop(["year_built","operating_for","leased_from","on_behalf_of","probable_cause"],axis=1,inplace=True)

motif=re.compile(r"^\s$")
for col in dframe.columns :
    for i in dframe.index :
        if str(dframe.loc[i,col])=="nan" or bool(motif.match(str(dframe.loc[i,col]))) or str(dframe.loc[i,col])=="?" or str(dframe.loc[i,col])=='':
            dframe.loc[i,col]="-"

for col in dfrecord.columns :
    for i in dfrecord.index :
        if str(dfrecord.loc[i,col])=="nan" or bool(motif.match(str(dfrecord.loc[i,col]))) or str(dfrecord.loc[i,col])=="?" or str(dfrecord.loc[i,col])=='':
            dfrecord.loc[i,col]="-"

In [9]:
n=dframe.shape[0]
colonne=["-" for i in range(n)]
dframe.insert(1,"week_day",colonne)
dic={"January":"JAN","February":"FEB","March":"MAR","April":"APR","May":"MAY","June":"JUN","July":"JUL","August":"AUG","September":"SEP","October":"OCT","November":"NOV","December":"DEC"}
#dic.keys()

In [10]:
liste=[f"{j}" for j in range(1,10)]
for i in dframe.index :
    date = dframe.loc[i,"date"].split(sep=" ")
    if len(date)==4 :
        dframe.loc[i,"week_day"]=date[0]
        if date[1] in liste : date[1]="0"+date[1]
        dframe.loc[i,"date"] = date[1]+"-"+dic[date[2]]+"-"+date[3]
    if len(date)==3 :
        if date[0] in liste : date[0]="0"+date[0]
        if date[1] in dic.keys():
            dframe.loc[i,"date"] = date[0]+"-"+dic[date[1]]+"-"+date[2]
        else :
            dframe.loc[i,"date"] = date[0]+"-"+date[1]+"-"+date[2]
    if len(date) ==2 :
        if date[0] in dic.keys() :
            dframe.loc[i,"date"] = "xx"+"-"+dic[date[0]]+"-"+date[1]
        else :
            dframe.loc[i,"date"] = "xx"+"-"+date[0]+"-"+date[1]
    if len(date) == 1:
        dframe.loc[i,"date"] = "xx"+"-"+"xxx"+"-"+date[0]

In [11]:
for i in dfrecord.index :
    date = dfrecord.loc[i,"date"].split(sep="-")
    if len(date) >= 2 :
        if date[1] not in dic.values():
            dfrecord.loc[i,"date"] = "xx"+"-"+"xxx"+"-"+date[2]
        elif date[0]=="??" :
            dfrecord.loc[i,"date"] = "xx"+"-"+date[1]+"-"+date[2]
    else :
        dfrecord.loc[i,"date"] = "xx"+"-"+"xxx"+"-"+date[0]

In [12]:
dframe.insert(4,"type_event",colonne)

In [13]:
for i in dfrecord.index :
    dfrecord.location[i]=dfrecord.location[i].strip("...")

In [14]:
for i in dframe.index :
    identifiant=dframe.loc[i,"identifiant"]
    df=dfrecord[dfrecord.identifiant==identifiant]
    if df.shape[0]==1 :  
        dframe.type_event[i]=df.type_event[df.index[0]]
        operator = df.operator[df.index[0]]
        operator_i = re.compile(r"^[^,]+")
        found=operator_i.search(operator)
        dframe.operator[i] = found.group()
    else :
        print(f"échec pour l'élément {i} : {df.shape[0]} correspondances possibles")

In [15]:
dframe[dframe.type_event=="-"]

Empty DataFrame
Columns: [identifiant, week_day, status, date, type_event, time, type_aircraft, operator, registration, c_n_msn, first_flight, total_airframe_hrs, engines, cycles, crew, passengers, ground_casualties, collision_casualties, aircraft_damage, aircraft_fate, location, phase, nature, departure_airport, destination_airport, flight_number, total]
Index: []

[0 rows x 27 columns]

In [16]:
dframe.columns

Index(['identifiant', 'week_day', 'status', 'date', 'type_event', 'time',
       'type_aircraft', 'operator', 'registration', 'c_n_msn', 'first_flight',
       'total_airframe_hrs', 'engines', 'cycles', 'crew', 'passengers',
       'ground_casualties', 'collision_casualties', 'aircraft_damage',
       'aircraft_fate', 'location', 'phase', 'nature', 'departure_airport',
       'destination_airport', 'flight_number', 'total'],
      dtype='object')

In [17]:
#motif_i = re.compile(r"(\d*)\s/\s\D+(\d*)")
#found = motif_i.search(dframe.crew[221])
#bool(found)
#found.groups()
#found.group(1)
#found.group(2)
#dframe.crew
#int('')

In [18]:
#dframe.location
#location=dframe.location[0]
#motif_i = re.compile(r"^(.*?)\s+\(\s+(\D.*)\)")
#found = motif_i.search(location)
#bool(found)
#found.group(1)
#found.group(2)

In [19]:
#engines = dframe.engines[0]
#motif_i = re.compile(r"^\s(\d+)\s(.+)$")
#found = motif_i.search(engines)
#print(bool(found))
#dframe.engines
#engines

In [20]:
#airport=dframe.departure_airport[0]
#airport=dframe.departure_airport[1]
#motif_i = re.compile(r"^([^,]*),?.*?\s+\((...)/(....)\),\s(.*)$")
#found = motif_i.search(airport)
#print(bool(found))
#print(found.groups())
#airport
#dframe.departure_airport
#nom="ground_casualties"
#casualties=dframe.loc[1418,nom]
#print(casualties)
#motif_i = re.compile(r"\d+")
#found = motif_i.search(casualties)
#print(bool(found))
#found.group()

In [21]:
dframe["country"]=colonne
dframe["total_occupants"]=colonne
dframe["total_fatalities"]=colonne
dframe["number_engines"]=colonne
dframe["type_engines"]=colonne
dframe["crew_number"]=colonne
dframe["passengers_number"]=colonne
dframe["crew_fatalities"]=colonne
dframe["passengers_fatalities"]=colonne
dframe["departure_airport_name"]=colonne
dframe["departure_airport_IATA"]=colonne
dframe["departure_airport_ICAO"]=colonne
dframe["departure_airport_country"]=colonne
dframe["destination_airport_name"]=colonne
dframe["destination_airport_IATA"]=colonne
dframe["destination_airport_ICAO"]=colonne
dframe["destination_airport_country"]=colonne

In [22]:
for i in dframe.index :
    
    time = dframe.time[i]
    motif_i = re.compile(r"\d\d:\d\d")
    found = motif_i.search(time)
    if bool(found) :
        dframe.time[i] = found.group()
    
    engines = dframe.engines[i]
    motif_i = re.compile(r"^\s(\d+)\s(.+)$")
    found = motif_i.search(engines)
    if bool(found) :
        dframe.number_engines[i] = found.group(1)
        dframe.type_engines[i] = found.group(2)
    else :
        dframe.type_engines[i]=engines
    
    crew = dframe.crew[i]
    motif_i = re.compile(r"(\d*)\s/\s\D+(\d*)")
    found = motif_i.search(crew)
    try :
        dframe.crew_fatalities[i] = int(found.group(1))
    except ValueError as err :
        dframe.crew_fatalities[i]="-"
    try :
        dframe.crew_number[i] = int(found.group(2))
    except ValueError as err :
        dframe.crew_number[i]="-"
        
    passengers = dframe.passengers[i]
    motif_i = re.compile(r"(\d*)\s/\s\D+(\d*)")
    found = motif_i.search(passengers)
    try :
        dframe.passengers_fatalities[i] = int(found.group(1))
    except ValueError as err :
        dframe.passengers_fatalities[i]="-"
    try :
        dframe.passengers_number[i] = int(found.group(2))
    except ValueError as err :
        dframe.passengers_number[i]="-"
        
    total = dframe.total[i]
    motif_i = re.compile(r"(\d*)\s/\s\D+(\d*)")
    found = motif_i.search(total)
    try :
        dframe.total_fatalities[i] = int(found.group(1))
    except ValueError as err :
        dframe.total_fatalities[i]="-"
    try :
        dframe.total_occupants[i] = int(found.group(2))
    except ValueError as err :
        dframe.total_occupants[i]="-"
    
    location=dframe.location[i]
    motif_i = re.compile(r"^(.*?)\s+\(\s+(\D.*)\)")
    found = motif_i.search(location)
    dframe.location[i]=found.group(1)
    dframe.country[i]=found.group(2)
    
    for nom in ["departure_airport","destination_airport"] :
        airport=dframe.loc[i,nom]
        motif_i = re.compile(r"^([^,]*),?.*?\s+\((...)/(....)\),\s(.*)$")
        found = motif_i.search(airport)
        if bool(found) :
            dframe.loc[i,f"{nom}_name"] = found.group(1)
            dframe.loc[i,f"{nom}_IATA"] = found.group(2)
            dframe.loc[i,f"{nom}_ICAO"] = found.group(3)
            dframe.loc[i,f"{nom}_country"] = found.group(4)
    
    for nom in ["ground_casualties","collision_casualties"] :
        casualties=dframe.loc[i,nom]
        motif_i = re.compile(r"\d+")
        found = motif_i.search(casualties)
        if bool(found) :
            dframe.loc[i,nom] = int(found.group())

In [23]:
dframe.head(8)

,identifiant,week_day,status,date,type_event,time,type_aircraft,operator,registration,c_n_msn,...,crew_fatalities,passengers_fatalities,departure_airport_name,departure_airport_IATA,departure_airport_ICAO,departure_airport_country,destination_airport_name,destination_airport_IATA,destination_airport_ICAO,destination_airport_country
0,20070101-0,Monday,Final,01-JAN-2007,A1,14:59,Boeing 737-4Q8,AdamAir,PK-KKW,24070/1665,...,6,96,Surabaya-Juanda Airport,SUB,WARR,Indonesia,Manado-Sam Ratulangi Airport,MDC,WAMM,Indonesia
1,20070107-0,Sunday,Final,07-JAN-2007,A1,20:02,Beechcraft A100 King Air,Transwest Air,C-GFFN,B-190,...,1,0,La Ronge Airport,YVC,CYVC,Canada,-,-,-,-
2,20070109-0,Tuesday,Preliminary,09-JAN-2007,A1,-,Antonov An-26B-100,Aeriantur-M Airlines,ER-26068,11308,...,5,29,Adana Airport,ADA,LTAF,Turkey,-,-,-,-
3,20070109-1,Tuesday,Preliminary - official,09-JAN-2007,A1,23:23,Learjet 24F,Ameristar Jet Charter,N444TW,24-348,...,2,0,Laredo International Airport,LRD,KLRD,United States of America,Guadalajara-Don Miguel Hidalgo y Costilla Inte...,GDL,MMGL,Mexico
4,20070109-2,Tuesday,Final,09-JAN-2007,A1,11:33,British Aerospace 3112 Jetstream 31,Peace Air,C-FBIP,820,...,0,0,Grande Prairie Airport,YQU,CYQU,Canada,Fort St. John Airport,YXJ,CYXJ,Canada
5,20070110-0,Wednesday,Final,10-JAN-2007,A1,03:30,Learjet 35A,AirNet Systems,N40AN,35A-271,...,0,0,Jacksonville International Airport,JAX,KJAX,United States of America,-,-,-,-
6,20070111-0,Thursday,Final,11-JAN-2007,A2,23:50,CASA/IPTN NC-212 Aviocar 200,Aviastar Mandiri,PK-BRM,412/92N,...,0,0,Balikpapan-Sepingan Airport,BPN,WALL,Indonesia,-,-,-,-
7,20070112-0,Friday,Final,12-JAN-2007,A1,11:07,Cessna 525 CitationJet,SunQuest,N77215,525-0149,...,2,0,Los Angeles-Van Nuys Airport,VNY,KVNY,United States of America,Long Beach Municipal Airport,LGB,KLGB,United States of America

In [24]:
dframe.columns

Index(['identifiant', 'week_day', 'status', 'date', 'type_event', 'time',
       'type_aircraft', 'operator', 'registration', 'c_n_msn', 'first_flight',
       'total_airframe_hrs', 'engines', 'cycles', 'crew', 'passengers',
       'ground_casualties', 'collision_casualties', 'aircraft_damage',
       'aircraft_fate', 'location', 'phase', 'nature', 'departure_airport',
       'destination_airport', 'flight_number', 'total', 'country',
       'total_occupants', 'total_fatalities', 'number_engines', 'type_engines',
       'crew_number', 'passengers_number', 'crew_fatalities',
       'passengers_fatalities', 'departure_airport_name',
       'departure_airport_IATA', 'departure_airport_ICAO',
       'departure_airport_country', 'destination_airport_name',
       'destination_airport_IATA', 'destination_airport_ICAO',
       'destination_airport_country'],
      dtype='object')

In [25]:
dframe.drop(["engines","crew","passengers","total","departure_airport","destination_airport"],axis=1,inplace=True)

In [26]:
print(len(dframe.columns))
print(len(final_names))

38
38

In [27]:
dframe=dframe.reindex(columns=final_names)

In [28]:
dframe

,identifiant,week_day,date,time,type_event,phase,location,country,total_occupants,total_fatalities,...,destination_airport_IATA,destination_airport_ICAO,destination_airport_country,crew_number,passengers_number,crew_fatalities,passengers_fatalities,collision_casualties,ground_casualties,status
0,20070101-0,Monday,01-JAN-2007,14:59,A1,En route (ENR),85 km (53.1 mls) W off Pambauang,Indonesia,102,102,...,MDC,WAMM,Indonesia,6,96,6,96,-,-,Final
1,20070107-0,Sunday,07-JAN-2007,20:02,A1,Approach (APR),"Sandy Bay Airport, SK",Canada,4,1,...,-,-,-,2,2,1,0,-,-,Final
2,20070109-0,Tuesday,09-JAN-2007,-,A1,Approach (APR),near Balad Air Base,Iraq,35,34,...,-,-,-,5,30,5,29,-,-,Preliminary
3,20070109-1,Tuesday,09-JAN-2007,23:23,A1,Approach (APR),30 km (18.8 mls) E of Guadalajara-Miguel Hidal...,Mexico,2,2,...,GDL,MMGL,Mexico,2,0,2,0,-,-,Preliminary - official
4,20070109-2,Tuesday,09-JAN-2007,11:33,A1,Landing (LDG),"Fort St. John Airport, BC (YXJ)",Canada,12,0,...,YXJ,CYXJ,Canada,2,10,0,0,-,-,Final
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,20071230-0,Sunday,30-DEC-2007,11:30,A1,Approach (APR),off Sabang,Indonesia,7,5,...,MES,WIMM,Indonesia,7,0,5,0,-,-,Preliminary
220,20071230-1,Sunday,30-DEC-2007,11:27,A1,Takeoff (TOF),Bucharest-Otopeni International Airport (OTP),Romania,123,0,...,SSH,HESH,Egypt,6,117,0,0,-,-,Final
221,20071231-0,Monday,31-DEC-2007,-,A2,Landing (LDG),Freetown-Lungi International Airport (FNA),Sierra Leone,-,0,...,FNA,GFLL,Sierra Leone,-,-,0,0,-,-,Preliminary
222,20079999-0,-,xx-xxx-2007,-,A1,Landing (LDG),Bunia Airport (BUX),Democratic Republic of the Congo,-,0,...,BUX,FZKA,Democratic Republic of the Congo,-,-,0,0,-,-,Preliminary
223,20079999-1,-,xx-xxx-2007,-,O1,Standing (STD),"Mojave Air & Space Port, CA (MHV)",United States of America,0,0,...,-,-,-,0,0,0,0,-,-,-

#help(pd.DataFrame.to_csv)

In [29]:
dframe.to_csv(f"donnees_traitees/data_{annee}.csv",index=False,header=True)